app:
    datasource:
        main:
            driver-class-name: org.postgresql.Driver
            jdbc-url: jdbc:postgresql://localhost:5432/jdbc_api
            username: postgres
            password: 'admin'
            pool-size: 30
server:
    error:
        include-binding-errors: always
        include-message: always